<center><h1> ABALONE </h1></center>

<img align="center" src="./images/abalone_shell.jpg" alt="Drawing" width="200"/>

------------------------------------------------------------------

## Determine the sex of abalone for given features

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv('./data/abalone_original.csv')

In [11]:
df.head()

sex  length  diameter  height  whole-weight  shucked-weight  viscera-weight  \
0   M      91        73      19         102.8            44.9            20.2   
1   M      70        53      18          45.1            19.9             9.7   
2   F     106        84      27         135.4            51.3            28.3   
3   M      88        73      25         103.2            43.1            22.8   
4   I      66        51      16          41.0            17.9             7.9   

   shell-weight  rings  
0          30.0     15  
1          14.0      7  
2          42.0      9  
3          31.0     10  
4          11.0      7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
sex               4177 non-null object
length            4177 non-null int64
diameter          4177 non-null int64
height            4177 non-null int64
whole-weight      4177 non-null float64
shucked-weight    4177 non-null float64
viscera-weight    4177 non-null float64
shell-weight      4177 non-null float64
rings             4177 non-null int64
dtypes: float64(4), int64(4), object(1)
memory usage: 293.8+ KB


In [5]:
df.describe()

length     diameter       height  whole-weight  shucked-weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean    104.798420    81.576251    27.903280    165.748432       71.873498   
std      24.018583    19.847973     8.365411     98.077804       44.392590   
min      15.000000    11.000000     0.000000      0.400000        0.200000   
25%      90.000000    70.000000    23.000000     88.300000       37.200000   
50%     109.000000    85.000000    28.000000    159.900000       67.200000   
75%     123.000000    96.000000    33.000000    230.600000      100.400000   
max     163.000000   130.000000   226.000000    565.100000      297.600000   

       viscera-weight  shell-weight        rings  
count     4177.000000   4177.000000  4177.000000  
mean        36.118722     47.766172     9.933684  
std         21.922850     27.840534     3.224169  
min          0.100000      0.300000     1.000000  
25%         18.700000     26.000000     8.000000  
50%         34.200000     46.800000     9.000000  
75%         50.600000     65.800000    11.000000  
max        152.000000    201.000000    29.000000

In [13]:
X = df.drop('sex',axis=1)
y = df['sex']

In [14]:
y.unique()

array(['M', 'F', 'I'], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

In [23]:
y_enc = enc.fit_transform(y.values.reshape(-1,1)).toarray()

In [27]:
print("Shape of output is ",y_enc.shape)
print(y_enc)

Shape of output is  (4177, 3)
[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [7]:
y = y.apply(lambda t: 1 if t =='M' elif t=='F' 0)

In [10]:
y.unique()

array([1, 0], dtype=int64)

In [8]:
# work with this dataset later
# df2 = sns.load_dataset('tips')

In [9]:
# df2.head(10)